/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const JavaCodeSnippet = IDL.Record({
  'output' : IDL.Opt(IDL.Text),
  'code' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUserJavaCode' : IDL.Func([], [], []),
  'deleteUserJavaCode' : IDL.Func([Time], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCodeSnippet' : IDL.Func([Time], [IDL.Opt(JavaCodeSnippet)], ['query']),
  'getJavaCodeSnippetsMeta' : IDL.Func(
      [],
      [IDL.Vec(JavaCodeSnippet)],
      ['query'],
    ),
  'getUserJavaCode' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JavaCodeSnippet)],
      ['query'],
    ),
  'getUserJavaCodeSnippets' : IDL.Func(
      [],
      [IDL.Vec(JavaCodeSnippet)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJavaCodeSnippets' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JavaCodeSnippet)],
      ['query'],
    ),
  'submitJavaCode' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const JavaCodeSnippet = IDL.Record({
    'output' : IDL.Opt(IDL.Text),
    'code' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUserJavaCode' : IDL.Func([], [], []),
    'deleteUserJavaCode' : IDL.Func([Time], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCodeSnippet' : IDL.Func([Time], [IDL.Opt(JavaCodeSnippet)], ['query']),
    'getJavaCodeSnippetsMeta' : IDL.Func(
        [],
        [IDL.Vec(JavaCodeSnippet)],
        ['query'],
      ),
    'getUserJavaCode' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JavaCodeSnippet)],
        ['query'],
      ),
    'getUserJavaCodeSnippets' : IDL.Func(
        [],
        [IDL.Vec(JavaCodeSnippet)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJavaCodeSnippets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JavaCodeSnippet)],
        ['query'],
      ),
    'submitJavaCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };